# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ipc_interactor_pb2 as ipc__interactor__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ipc_interactor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InternalIpcInteractorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.listCardsByAccount = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/listCardsByAccount',
                request_serializer=ipc__interactor__pb2.ListCardsByAccountRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.ListCardsByAccountResponse.FromString,
                _registered_method=True)
        self.listAccountsByCard = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/listAccountsByCard',
                request_serializer=ipc__interactor__pb2.ListAccountsByCardRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.ListAccountsByCardResponse.FromString,
                _registered_method=True)
        self.editCard = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/editCard',
                request_serializer=ipc__interactor__pb2.EditCardRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.EditCardResponse.FromString,
                _registered_method=True)
        self.addCardToStop = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/addCardToStop',
                request_serializer=ipc__interactor__pb2.AddCardToStopRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.AddCardToStopResponse.FromString,
                _registered_method=True)
        self.removeCardFromStop = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/removeCardFromStop',
                request_serializer=ipc__interactor__pb2.RemoveCardFromStopRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.RemoveCardFromStopResponse.FromString,
                _registered_method=True)
        self.getCardholderNameByPan = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/getCardholderNameByPan',
                request_serializer=ipc__interactor__pb2.GetCardholderNameByPanRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.GetCardholderNameByPanResponse.FromString,
                _registered_method=True)
        self.getCardAccountsBalance = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/getCardAccountsBalance',
                request_serializer=ipc__interactor__pb2.GetCardAccountsBalanceRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.GetCardAccountsBalanceResponse.FromString,
                _registered_method=True)
        self.getTransactions = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/getTransactions',
                request_serializer=ipc__interactor__pb2.GetTransactionsRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.GetTransactionsResponse.FromString,
                _registered_method=True)
        self.assignPin = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/assignPin',
                request_serializer=ipc__interactor__pb2.AssignPinRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.AssignPinResponse.FromString,
                _registered_method=True)
        self.unblockCard = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/unblockCard',
                request_serializer=ipc__interactor__pb2.UnblockCardRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.UnblockCardResponse.FromString,
                _registered_method=True)
        self.addCardInfoByAccId = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/addCardInfoByAccId',
                request_serializer=ipc__interactor__pb2.AddCardPanByAccIdRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.AddCardPanByAccIdResponse.FromString,
                _registered_method=True)
        self.syncCardData = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/syncCardData',
                request_serializer=ipc__interactor__pb2.SyncCardDataRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.SyncCardDataResponse.FromString,
                _registered_method=True)
        self.getCardAccountsBalanceByAccountNo = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/getCardAccountsBalanceByAccountNo',
                request_serializer=ipc__interactor__pb2.GetCardAccountsBalanceByAccountNoRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.GetCardAccountsBalanceResponse.FromString,
                _registered_method=True)
        self.getCardBalance = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/getCardBalance',
                request_serializer=ipc__interactor__pb2.GetCardBalanceRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.GetCardAccountsBalanceResponse.FromString,
                _registered_method=True)
        self.getTransactionsByAccId = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/getTransactionsByAccId',
                request_serializer=ipc__interactor__pb2.GetTransactionsRequestByAccId.SerializeToString,
                response_deserializer=ipc__interactor__pb2.GetTransactionsResponse.FromString,
                _registered_method=True)
        self.cardCreditSecondStepByAccId = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/cardCreditSecondStepByAccId',
                request_serializer=ipc__interactor__pb2.CardCreditSecondStepRequestByAccId.SerializeToString,
                response_deserializer=ipc__interactor__pb2.CardCreditSecondStepResponse.FromString,
                _registered_method=True)
        self.cardDebitSecondStepByAccId = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/cardDebitSecondStepByAccId',
                request_serializer=ipc__interactor__pb2.CardDebitSecondStepRequestByAccId.SerializeToString,
                response_deserializer=ipc__interactor__pb2.CardDebitSecondStepResponse.FromString,
                _registered_method=True)
        self.getCardPanByAccIdD = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/getCardPanByAccIdD',
                request_serializer=ipc__interactor__pb2.GetCardPanByAccIdDRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.GetCardPanByAccIdDResponse.FromString,
                _registered_method=True)
        self.addCardToStopByAccId = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/addCardToStopByAccId',
                request_serializer=ipc__interactor__pb2.AddCardToStopByAccIdRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.AddCardToStopResponse.FromString,
                _registered_method=True)
        self.removeCardFromStopByAccId = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/removeCardFromStopByAccId',
                request_serializer=ipc__interactor__pb2.RemoveCardFromStopByAccIdRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.RemoveCardFromStopResponse.FromString,
                _registered_method=True)
        self.cardCreditFirstStep = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/cardCreditFirstStep',
                request_serializer=ipc__interactor__pb2.Empty.SerializeToString,
                response_deserializer=ipc__interactor__pb2.CardCreditFirstStepResponse.FromString,
                _registered_method=True)
        self.cardCreditSecondStep = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/cardCreditSecondStep',
                request_serializer=ipc__interactor__pb2.CardCreditSecondStepRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.CardCreditSecondStepResponse.FromString,
                _registered_method=True)
        self.cardDebitFirstStep = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/cardDebitFirstStep',
                request_serializer=ipc__interactor__pb2.Empty.SerializeToString,
                response_deserializer=ipc__interactor__pb2.CardDebitFirstStepResponse.FromString,
                _registered_method=True)
        self.cardDebitSecondStep = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/cardDebitSecondStep',
                request_serializer=ipc__interactor__pb2.CardDebitSecondStepRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.CardDebitSecondStepResponse.FromString,
                _registered_method=True)
        self.reverseCardCreditOrDebitFirstStep = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/reverseCardCreditOrDebitFirstStep',
                request_serializer=ipc__interactor__pb2.Empty.SerializeToString,
                response_deserializer=ipc__interactor__pb2.ReverseCardCreditOrDebitFirstStepResponse.FromString,
                _registered_method=True)
        self.reverseCardCreditOrDebitSecondStep = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/reverseCardCreditOrDebitSecondStep',
                request_serializer=ipc__interactor__pb2.ReverseCardCreditOrDebitSecondStepRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.ReverseCardCreditOrDebitSecondStepResponse.FromString,
                _registered_method=True)
        self.registrationOfNewCardToSmsService = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/registrationOfNewCardToSmsService',
                request_serializer=ipc__interactor__pb2.RegistrationOfNewCardToSmsServiceRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.SmsServiceResponse.FromString,
                _registered_method=True)
        self.registrationOfAnotherBaseCardToSmsService = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/registrationOfAnotherBaseCardToSmsService',
                request_serializer=ipc__interactor__pb2.RegistrationOfAnotherBaseCardToSmsServiceRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.SmsServiceResponse.FromString,
                _registered_method=True)
        self.registrationOfSuppCardToSmsService = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/registrationOfSuppCardToSmsService',
                request_serializer=ipc__interactor__pb2.RegistrationOfSuppCardToSmsServiceRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.SmsServiceResponse.FromString,
                _registered_method=True)
        self.configureIpcSmsNotifications = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/configureIpcSmsNotifications',
                request_serializer=ipc__interactor__pb2.ConfigureSmsNotificationsRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.SmsServiceResponse.FromString,
                _registered_method=True)
        self.makeCardToCardPaymentFirstStep = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/makeCardToCardPaymentFirstStep',
                request_serializer=ipc__interactor__pb2.Empty.SerializeToString,
                response_deserializer=ipc__interactor__pb2.MakeCardToCardPaymentFirstStepResponse.FromString,
                _registered_method=True)
        self.makeCardToCardPaymentSecondStep = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/makeCardToCardPaymentSecondStep',
                request_serializer=ipc__interactor__pb2.MakeCardToCardPaymentSecondStepRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.MakeCardToCardPaymentSecondStepResponse.FromString,
                _registered_method=True)
        self.queryCardInfo = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/queryCardInfo',
                request_serializer=ipc__interactor__pb2.QueryCardInfoRequest.SerializeToString,
                response_deserializer=ipc__interactor__pb2.QueryCardInfoResponse.FromString,
                _registered_method=True)
        self.getCvv2 = channel.unary_unary(
                '/internal_ipc_interactor.InternalIpcInteractor/getCvv2',
                request_serializer=ipc__interactor__pb2.GetCvv2Request.SerializeToString,
                response_deserializer=ipc__interactor__pb2.GetCvv2Response.FromString,
                _registered_method=True)


class InternalIpcInteractorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def listCardsByAccount(self, request, context):
        """IPC Back services. URL: https://10.100.101.126:8443/issuingws/services/Issuing
        карта клиента по номеру счета
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listAccountsByCard(self, request, context):
        """все карты клиента по номеру карты (любой)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def editCard(self, request, context):
        """Подключение или отключение карты к интернет оплате
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addCardToStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def removeCardFromStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCardholderNameByPan(self, request, context):
        """Получение имени картодержателя по PAN (Elcard)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCardAccountsBalance(self, request, context):
        """New IPC Services for get Balance and get Statement URL(https://10.100.100.103:6677)
        get balance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTransactions(self, request, context):
        """get statements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def assignPin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unblockCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addCardInfoByAccId(self, request, context):
        """Custom method to get card, account and balance info and etc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def syncCardData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCardAccountsBalanceByAccountNo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCardBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTransactionsByAccId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cardCreditSecondStepByAccId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cardDebitSecondStepByAccId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCardPanByAccIdD(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addCardToStopByAccId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def removeCardFromStopByAccId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cardCreditFirstStep(self, request, context):
        """IPC FRONT Services URL(https://10.100.100.103:7777)
        Пополнение карты первый шаг
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cardCreditSecondStep(self, request, context):
        """Пополнение карты второй шаг
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cardDebitFirstStep(self, request, context):
        """Дебитование карты первый шаг
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cardDebitSecondStep(self, request, context):
        """Дебитование карты второй шаг
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reverseCardCreditOrDebitFirstStep(self, request, context):
        """Отмена дебитования/кредитования карты первый шаг
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reverseCardCreditOrDebitSecondStep(self, request, context):
        """Отмена дебитования/кредитования карты второй шаг
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registrationOfNewCardToSmsService(self, request, context):
        """Функционал с смс уведомлениями
        Регистрация
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registrationOfAnotherBaseCardToSmsService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registrationOfSuppCardToSmsService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def configureIpcSmsNotifications(self, request, context):
        """Активация/деактивация
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def makeCardToCardPaymentFirstStep(self, request, context):
        """Переводы с карты на карты чужого банка, для реверса используем методы reverseCardCreditOrDebitFirstStep и reverseCardCreditOrDebitSecondStep
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def makeCardToCardPaymentSecondStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryCardInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCvv2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalIpcInteractorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'listCardsByAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.listCardsByAccount,
                    request_deserializer=ipc__interactor__pb2.ListCardsByAccountRequest.FromString,
                    response_serializer=ipc__interactor__pb2.ListCardsByAccountResponse.SerializeToString,
            ),
            'listAccountsByCard': grpc.unary_unary_rpc_method_handler(
                    servicer.listAccountsByCard,
                    request_deserializer=ipc__interactor__pb2.ListAccountsByCardRequest.FromString,
                    response_serializer=ipc__interactor__pb2.ListAccountsByCardResponse.SerializeToString,
            ),
            'editCard': grpc.unary_unary_rpc_method_handler(
                    servicer.editCard,
                    request_deserializer=ipc__interactor__pb2.EditCardRequest.FromString,
                    response_serializer=ipc__interactor__pb2.EditCardResponse.SerializeToString,
            ),
            'addCardToStop': grpc.unary_unary_rpc_method_handler(
                    servicer.addCardToStop,
                    request_deserializer=ipc__interactor__pb2.AddCardToStopRequest.FromString,
                    response_serializer=ipc__interactor__pb2.AddCardToStopResponse.SerializeToString,
            ),
            'removeCardFromStop': grpc.unary_unary_rpc_method_handler(
                    servicer.removeCardFromStop,
                    request_deserializer=ipc__interactor__pb2.RemoveCardFromStopRequest.FromString,
                    response_serializer=ipc__interactor__pb2.RemoveCardFromStopResponse.SerializeToString,
            ),
            'getCardholderNameByPan': grpc.unary_unary_rpc_method_handler(
                    servicer.getCardholderNameByPan,
                    request_deserializer=ipc__interactor__pb2.GetCardholderNameByPanRequest.FromString,
                    response_serializer=ipc__interactor__pb2.GetCardholderNameByPanResponse.SerializeToString,
            ),
            'getCardAccountsBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.getCardAccountsBalance,
                    request_deserializer=ipc__interactor__pb2.GetCardAccountsBalanceRequest.FromString,
                    response_serializer=ipc__interactor__pb2.GetCardAccountsBalanceResponse.SerializeToString,
            ),
            'getTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.getTransactions,
                    request_deserializer=ipc__interactor__pb2.GetTransactionsRequest.FromString,
                    response_serializer=ipc__interactor__pb2.GetTransactionsResponse.SerializeToString,
            ),
            'assignPin': grpc.unary_unary_rpc_method_handler(
                    servicer.assignPin,
                    request_deserializer=ipc__interactor__pb2.AssignPinRequest.FromString,
                    response_serializer=ipc__interactor__pb2.AssignPinResponse.SerializeToString,
            ),
            'unblockCard': grpc.unary_unary_rpc_method_handler(
                    servicer.unblockCard,
                    request_deserializer=ipc__interactor__pb2.UnblockCardRequest.FromString,
                    response_serializer=ipc__interactor__pb2.UnblockCardResponse.SerializeToString,
            ),
            'addCardInfoByAccId': grpc.unary_unary_rpc_method_handler(
                    servicer.addCardInfoByAccId,
                    request_deserializer=ipc__interactor__pb2.AddCardPanByAccIdRequest.FromString,
                    response_serializer=ipc__interactor__pb2.AddCardPanByAccIdResponse.SerializeToString,
            ),
            'syncCardData': grpc.unary_unary_rpc_method_handler(
                    servicer.syncCardData,
                    request_deserializer=ipc__interactor__pb2.SyncCardDataRequest.FromString,
                    response_serializer=ipc__interactor__pb2.SyncCardDataResponse.SerializeToString,
            ),
            'getCardAccountsBalanceByAccountNo': grpc.unary_unary_rpc_method_handler(
                    servicer.getCardAccountsBalanceByAccountNo,
                    request_deserializer=ipc__interactor__pb2.GetCardAccountsBalanceByAccountNoRequest.FromString,
                    response_serializer=ipc__interactor__pb2.GetCardAccountsBalanceResponse.SerializeToString,
            ),
            'getCardBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.getCardBalance,
                    request_deserializer=ipc__interactor__pb2.GetCardBalanceRequest.FromString,
                    response_serializer=ipc__interactor__pb2.GetCardAccountsBalanceResponse.SerializeToString,
            ),
            'getTransactionsByAccId': grpc.unary_unary_rpc_method_handler(
                    servicer.getTransactionsByAccId,
                    request_deserializer=ipc__interactor__pb2.GetTransactionsRequestByAccId.FromString,
                    response_serializer=ipc__interactor__pb2.GetTransactionsResponse.SerializeToString,
            ),
            'cardCreditSecondStepByAccId': grpc.unary_unary_rpc_method_handler(
                    servicer.cardCreditSecondStepByAccId,
                    request_deserializer=ipc__interactor__pb2.CardCreditSecondStepRequestByAccId.FromString,
                    response_serializer=ipc__interactor__pb2.CardCreditSecondStepResponse.SerializeToString,
            ),
            'cardDebitSecondStepByAccId': grpc.unary_unary_rpc_method_handler(
                    servicer.cardDebitSecondStepByAccId,
                    request_deserializer=ipc__interactor__pb2.CardDebitSecondStepRequestByAccId.FromString,
                    response_serializer=ipc__interactor__pb2.CardDebitSecondStepResponse.SerializeToString,
            ),
            'getCardPanByAccIdD': grpc.unary_unary_rpc_method_handler(
                    servicer.getCardPanByAccIdD,
                    request_deserializer=ipc__interactor__pb2.GetCardPanByAccIdDRequest.FromString,
                    response_serializer=ipc__interactor__pb2.GetCardPanByAccIdDResponse.SerializeToString,
            ),
            'addCardToStopByAccId': grpc.unary_unary_rpc_method_handler(
                    servicer.addCardToStopByAccId,
                    request_deserializer=ipc__interactor__pb2.AddCardToStopByAccIdRequest.FromString,
                    response_serializer=ipc__interactor__pb2.AddCardToStopResponse.SerializeToString,
            ),
            'removeCardFromStopByAccId': grpc.unary_unary_rpc_method_handler(
                    servicer.removeCardFromStopByAccId,
                    request_deserializer=ipc__interactor__pb2.RemoveCardFromStopByAccIdRequest.FromString,
                    response_serializer=ipc__interactor__pb2.RemoveCardFromStopResponse.SerializeToString,
            ),
            'cardCreditFirstStep': grpc.unary_unary_rpc_method_handler(
                    servicer.cardCreditFirstStep,
                    request_deserializer=ipc__interactor__pb2.Empty.FromString,
                    response_serializer=ipc__interactor__pb2.CardCreditFirstStepResponse.SerializeToString,
            ),
            'cardCreditSecondStep': grpc.unary_unary_rpc_method_handler(
                    servicer.cardCreditSecondStep,
                    request_deserializer=ipc__interactor__pb2.CardCreditSecondStepRequest.FromString,
                    response_serializer=ipc__interactor__pb2.CardCreditSecondStepResponse.SerializeToString,
            ),
            'cardDebitFirstStep': grpc.unary_unary_rpc_method_handler(
                    servicer.cardDebitFirstStep,
                    request_deserializer=ipc__interactor__pb2.Empty.FromString,
                    response_serializer=ipc__interactor__pb2.CardDebitFirstStepResponse.SerializeToString,
            ),
            'cardDebitSecondStep': grpc.unary_unary_rpc_method_handler(
                    servicer.cardDebitSecondStep,
                    request_deserializer=ipc__interactor__pb2.CardDebitSecondStepRequest.FromString,
                    response_serializer=ipc__interactor__pb2.CardDebitSecondStepResponse.SerializeToString,
            ),
            'reverseCardCreditOrDebitFirstStep': grpc.unary_unary_rpc_method_handler(
                    servicer.reverseCardCreditOrDebitFirstStep,
                    request_deserializer=ipc__interactor__pb2.Empty.FromString,
                    response_serializer=ipc__interactor__pb2.ReverseCardCreditOrDebitFirstStepResponse.SerializeToString,
            ),
            'reverseCardCreditOrDebitSecondStep': grpc.unary_unary_rpc_method_handler(
                    servicer.reverseCardCreditOrDebitSecondStep,
                    request_deserializer=ipc__interactor__pb2.ReverseCardCreditOrDebitSecondStepRequest.FromString,
                    response_serializer=ipc__interactor__pb2.ReverseCardCreditOrDebitSecondStepResponse.SerializeToString,
            ),
            'registrationOfNewCardToSmsService': grpc.unary_unary_rpc_method_handler(
                    servicer.registrationOfNewCardToSmsService,
                    request_deserializer=ipc__interactor__pb2.RegistrationOfNewCardToSmsServiceRequest.FromString,
                    response_serializer=ipc__interactor__pb2.SmsServiceResponse.SerializeToString,
            ),
            'registrationOfAnotherBaseCardToSmsService': grpc.unary_unary_rpc_method_handler(
                    servicer.registrationOfAnotherBaseCardToSmsService,
                    request_deserializer=ipc__interactor__pb2.RegistrationOfAnotherBaseCardToSmsServiceRequest.FromString,
                    response_serializer=ipc__interactor__pb2.SmsServiceResponse.SerializeToString,
            ),
            'registrationOfSuppCardToSmsService': grpc.unary_unary_rpc_method_handler(
                    servicer.registrationOfSuppCardToSmsService,
                    request_deserializer=ipc__interactor__pb2.RegistrationOfSuppCardToSmsServiceRequest.FromString,
                    response_serializer=ipc__interactor__pb2.SmsServiceResponse.SerializeToString,
            ),
            'configureIpcSmsNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.configureIpcSmsNotifications,
                    request_deserializer=ipc__interactor__pb2.ConfigureSmsNotificationsRequest.FromString,
                    response_serializer=ipc__interactor__pb2.SmsServiceResponse.SerializeToString,
            ),
            'makeCardToCardPaymentFirstStep': grpc.unary_unary_rpc_method_handler(
                    servicer.makeCardToCardPaymentFirstStep,
                    request_deserializer=ipc__interactor__pb2.Empty.FromString,
                    response_serializer=ipc__interactor__pb2.MakeCardToCardPaymentFirstStepResponse.SerializeToString,
            ),
            'makeCardToCardPaymentSecondStep': grpc.unary_unary_rpc_method_handler(
                    servicer.makeCardToCardPaymentSecondStep,
                    request_deserializer=ipc__interactor__pb2.MakeCardToCardPaymentSecondStepRequest.FromString,
                    response_serializer=ipc__interactor__pb2.MakeCardToCardPaymentSecondStepResponse.SerializeToString,
            ),
            'queryCardInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.queryCardInfo,
                    request_deserializer=ipc__interactor__pb2.QueryCardInfoRequest.FromString,
                    response_serializer=ipc__interactor__pb2.QueryCardInfoResponse.SerializeToString,
            ),
            'getCvv2': grpc.unary_unary_rpc_method_handler(
                    servicer.getCvv2,
                    request_deserializer=ipc__interactor__pb2.GetCvv2Request.FromString,
                    response_serializer=ipc__interactor__pb2.GetCvv2Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'internal_ipc_interactor.InternalIpcInteractor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('internal_ipc_interactor.InternalIpcInteractor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InternalIpcInteractor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def listCardsByAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/listCardsByAccount',
            ipc__interactor__pb2.ListCardsByAccountRequest.SerializeToString,
            ipc__interactor__pb2.ListCardsByAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listAccountsByCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/listAccountsByCard',
            ipc__interactor__pb2.ListAccountsByCardRequest.SerializeToString,
            ipc__interactor__pb2.ListAccountsByCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def editCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/editCard',
            ipc__interactor__pb2.EditCardRequest.SerializeToString,
            ipc__interactor__pb2.EditCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def addCardToStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/addCardToStop',
            ipc__interactor__pb2.AddCardToStopRequest.SerializeToString,
            ipc__interactor__pb2.AddCardToStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def removeCardFromStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/removeCardFromStop',
            ipc__interactor__pb2.RemoveCardFromStopRequest.SerializeToString,
            ipc__interactor__pb2.RemoveCardFromStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCardholderNameByPan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/getCardholderNameByPan',
            ipc__interactor__pb2.GetCardholderNameByPanRequest.SerializeToString,
            ipc__interactor__pb2.GetCardholderNameByPanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCardAccountsBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/getCardAccountsBalance',
            ipc__interactor__pb2.GetCardAccountsBalanceRequest.SerializeToString,
            ipc__interactor__pb2.GetCardAccountsBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/getTransactions',
            ipc__interactor__pb2.GetTransactionsRequest.SerializeToString,
            ipc__interactor__pb2.GetTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def assignPin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/assignPin',
            ipc__interactor__pb2.AssignPinRequest.SerializeToString,
            ipc__interactor__pb2.AssignPinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def unblockCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/unblockCard',
            ipc__interactor__pb2.UnblockCardRequest.SerializeToString,
            ipc__interactor__pb2.UnblockCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def addCardInfoByAccId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/addCardInfoByAccId',
            ipc__interactor__pb2.AddCardPanByAccIdRequest.SerializeToString,
            ipc__interactor__pb2.AddCardPanByAccIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def syncCardData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/syncCardData',
            ipc__interactor__pb2.SyncCardDataRequest.SerializeToString,
            ipc__interactor__pb2.SyncCardDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCardAccountsBalanceByAccountNo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/getCardAccountsBalanceByAccountNo',
            ipc__interactor__pb2.GetCardAccountsBalanceByAccountNoRequest.SerializeToString,
            ipc__interactor__pb2.GetCardAccountsBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCardBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/getCardBalance',
            ipc__interactor__pb2.GetCardBalanceRequest.SerializeToString,
            ipc__interactor__pb2.GetCardAccountsBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTransactionsByAccId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/getTransactionsByAccId',
            ipc__interactor__pb2.GetTransactionsRequestByAccId.SerializeToString,
            ipc__interactor__pb2.GetTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cardCreditSecondStepByAccId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/cardCreditSecondStepByAccId',
            ipc__interactor__pb2.CardCreditSecondStepRequestByAccId.SerializeToString,
            ipc__interactor__pb2.CardCreditSecondStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cardDebitSecondStepByAccId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/cardDebitSecondStepByAccId',
            ipc__interactor__pb2.CardDebitSecondStepRequestByAccId.SerializeToString,
            ipc__interactor__pb2.CardDebitSecondStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCardPanByAccIdD(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/getCardPanByAccIdD',
            ipc__interactor__pb2.GetCardPanByAccIdDRequest.SerializeToString,
            ipc__interactor__pb2.GetCardPanByAccIdDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def addCardToStopByAccId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/addCardToStopByAccId',
            ipc__interactor__pb2.AddCardToStopByAccIdRequest.SerializeToString,
            ipc__interactor__pb2.AddCardToStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def removeCardFromStopByAccId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/removeCardFromStopByAccId',
            ipc__interactor__pb2.RemoveCardFromStopByAccIdRequest.SerializeToString,
            ipc__interactor__pb2.RemoveCardFromStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cardCreditFirstStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/cardCreditFirstStep',
            ipc__interactor__pb2.Empty.SerializeToString,
            ipc__interactor__pb2.CardCreditFirstStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cardCreditSecondStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/cardCreditSecondStep',
            ipc__interactor__pb2.CardCreditSecondStepRequest.SerializeToString,
            ipc__interactor__pb2.CardCreditSecondStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cardDebitFirstStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/cardDebitFirstStep',
            ipc__interactor__pb2.Empty.SerializeToString,
            ipc__interactor__pb2.CardDebitFirstStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cardDebitSecondStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/cardDebitSecondStep',
            ipc__interactor__pb2.CardDebitSecondStepRequest.SerializeToString,
            ipc__interactor__pb2.CardDebitSecondStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def reverseCardCreditOrDebitFirstStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/reverseCardCreditOrDebitFirstStep',
            ipc__interactor__pb2.Empty.SerializeToString,
            ipc__interactor__pb2.ReverseCardCreditOrDebitFirstStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def reverseCardCreditOrDebitSecondStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/reverseCardCreditOrDebitSecondStep',
            ipc__interactor__pb2.ReverseCardCreditOrDebitSecondStepRequest.SerializeToString,
            ipc__interactor__pb2.ReverseCardCreditOrDebitSecondStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def registrationOfNewCardToSmsService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/registrationOfNewCardToSmsService',
            ipc__interactor__pb2.RegistrationOfNewCardToSmsServiceRequest.SerializeToString,
            ipc__interactor__pb2.SmsServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def registrationOfAnotherBaseCardToSmsService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/registrationOfAnotherBaseCardToSmsService',
            ipc__interactor__pb2.RegistrationOfAnotherBaseCardToSmsServiceRequest.SerializeToString,
            ipc__interactor__pb2.SmsServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def registrationOfSuppCardToSmsService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/registrationOfSuppCardToSmsService',
            ipc__interactor__pb2.RegistrationOfSuppCardToSmsServiceRequest.SerializeToString,
            ipc__interactor__pb2.SmsServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def configureIpcSmsNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/configureIpcSmsNotifications',
            ipc__interactor__pb2.ConfigureSmsNotificationsRequest.SerializeToString,
            ipc__interactor__pb2.SmsServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def makeCardToCardPaymentFirstStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/makeCardToCardPaymentFirstStep',
            ipc__interactor__pb2.Empty.SerializeToString,
            ipc__interactor__pb2.MakeCardToCardPaymentFirstStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def makeCardToCardPaymentSecondStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/makeCardToCardPaymentSecondStep',
            ipc__interactor__pb2.MakeCardToCardPaymentSecondStepRequest.SerializeToString,
            ipc__interactor__pb2.MakeCardToCardPaymentSecondStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def queryCardInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/queryCardInfo',
            ipc__interactor__pb2.QueryCardInfoRequest.SerializeToString,
            ipc__interactor__pb2.QueryCardInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCvv2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal_ipc_interactor.InternalIpcInteractor/getCvv2',
            ipc__interactor__pb2.GetCvv2Request.SerializeToString,
            ipc__interactor__pb2.GetCvv2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
